#!/bin/bash
TPU_NAME=v3-1
RESNETDEPTH=gala-v2_152
ANNOTATIONS=hms
DATA_DIR=gs://serrelab-public/clickme
PYTHON_PATH=$PYTHON_PATH:$(pwd)/tpu/models/official
BUCKET=gs://performances-tpu-$RESNETDEPTH-$ANNOTATIONS; \
# gsutil rm -r $BUCKET;
gsutil mkdir $BUCKET; \
python3 tpu/models/official/resnet/resnet_main.py \
  --tpu_name=$TPU_NAME \
  --data_dir=$DATA_DIR \
  --model_dir=$BUCKET \
  --annotation=$ANNOTATIONS \
  --resnet_depth=$RESNETDEPTH | tee -a performances-tpu-$RESNETDEPTH

